name: generate hosts file
on:
  push:
    branches:
      - master
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: cp hosts hosts.new
      - run: node index.js >> hosts.new
      - run: sort -u hosts.new > hosts
      - name: commit
        run: |
          git add hosts
          if ! git diff --cached --quiet --exit-code
          then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "generated" -m "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            git push
          fi
